name: TO BE VALIDATED

on: 
  pull_request:
    branches:
      - main
      
permissions: 
  contents: read

jobs:
  validate-pr:
    name: PR Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Feature Branch Naming
        run: |
          echo " Source Branch is '${{ github.head_ref }}' "
          if [[ ! $"{{ github.head_ref}}" =~ ^feature- ]]; then
            echo " Error: Branch name must start with feature- "
            exit 1
          fi
      - name: Validate workflow file exists
        run: |
          test -f .github/workflows/Greetingsworkflow.yml

          
